Article/urls.py
from django.urls import path
from . import views
from .views import ArticleDetailView

app_name = 'Articles'
urlpatterns = [
    path('detail/<slug:slug>', views.ArticleDetailView, name='article_detail'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like'),
]

ByteBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Index.urls')),
    path('articles/', include('Article.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Index/urls.py
from django.urls import path
from . import views
app_name = 'index'
urlpatterns = [
    path('', views.index, name='index'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like'),
    path('articles/list/<int:pk>', views.article_list, name='article_list'),
    path('about_me', views.about_me, name='about_me'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('search/', views.search, name='search'),
]

Article/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from Account.models import CustomUser


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='عنوان')
    created_time = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name='تاریخ انتشار')
    color = models.CharField(max_length=50, blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name='وضعیت انتشار')


    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان')
    body = RichTextField(verbose_name='مطلب')
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='نویسنده')
    category = models.ManyToManyField(Category, verbose_name='دسته بندی')
    image = models.ImageField(null=True, blank=True, upload_to='Article/images', verbose_name='تصویر')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')
    slug = models.SlugField(null=True, blank=True, unique=True, verbose_name='لینک مقاله')
    published = models.BooleanField(default=False, verbose_name='وضعیت انتشار')
    color = models.CharField(max_length=20, blank=True, null=True)

    def get_absolute_url(self):
        return reverse("Articles:article_detail", args=[self.slug])

    def save(
            self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        # self.slug = slugify(self.title)
        super(Article, self).save()

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'

    def __str__(self):
        return f"{self.title} - {self.author} - {self.created_time}"


class Like(models.Model):
    article = models.ForeignKey(Article, related_name='likes', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'لایک'
        verbose_name_plural = 'لایک ها'

    def __str__(self):
        return self.created_at


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments', verbose_name='مقاله')
    name = models.CharField(max_length=100, verbose_name='نام')
    email = models.EmailField(verbose_name='ایمیل')
    body = models.TextField(verbose_name='متن نظر')
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE, related_name='replies',
                               verbose_name='نظر والد')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت")
    published = models.BooleanField(default=False, verbose_name='وضعیت انتشار')


    class Meta:
        verbose_name = 'نظر'
        verbose_name_plural = 'نظرات'

    def __str__(self):
        return f"{self.name} - {self.email} - {self.article.title}"

Article/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.views.generic import DetailView
from .models import Article, Like, Comment


# class ArticleDetailView(DetailView):
#     model = Article
#     template_name = 'Article/ArticleDetail.html'
#     context_object_name = 'articles'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['like'] = Like.objects.all().filter(article__slug=self.object.slug, article_id=self.object.id)
#         context['liked'] = context['like'].filter(article__slug=self.object.slug, article_id=self.object.id)
#
#         # articles = self.get_object()
#         # context['comments'] = Comment.objects.filter(article=articles, published=True)
#
#         return context
#
#     def post(self, request, *args, **kwargs):
#         name = request.POST.get('name')
#         body = request.POST.get('body')
#         parent = request.POST.get('parent')
#         articles = self.get_object()
#         Comment.objects.create(article=articles, name=name, body=body, parent_id=parent)
#
#         context = self.get_context_data()
#         return self.render_to_response(context)

def ArticleDetailView(request, slug):
    articles = get_object_or_404(Article, slug=slug)
    like = Like.objects.all().filter(article__slug=articles.slug, article_id=articles.id)
    next_article = Article.objects.filter(created_time__gt=articles.created_time).order_by('created_time').first()
    prev_article = Article.objects.filter(created_time__lt=articles.created_time).order_by('-created_time').first()
    comments = Comment.objects.filter(article=articles, published=True).count()

    if request.method == 'POST':
        name = request.POST.get('name')
        body = request.POST.get('body')
        parent = request.POST.get('parent')
        email = request.POST.get('email')
        Comment.objects.create(article=articles, name=name, body=body, parent_id=parent, email=email)

    if like.filter(article__slug=articles.slug, article_id=articles.id):
        liked = True
    else:
        liked = False


    context = {
        'articles': articles,
        'like': like,
        'liked': liked,
        'comments': comments,
        'next_article': next_article,
        'prev_article': prev_article,
    }

    return render(request, 'Article/ArticleDetail.html', context)


def like(request, slug, pk):
    try:
        like = Like.objects.get(article__slug=slug)
        like.delete()
    except:
        Like.objects.create(article_id=pk)

    return redirect('Articles:article_detail', slug)

templates/includes/articles.html
{% load humanize %}
{% load static %}
{% load tz %}
<div class="col-lg-8 col-12">
    <section class="articles">
        {% for article in articles %}
            <article class="{{ article.color }}">
                <div class="articles-header">
                    {% if article.time_difference < 24 %}
                        <time datetime="2016-10-11">{{ article.time_difference|intword }} ساعت پیش </time>
                        <span class="articles-header-tag-blue">داغ</span>
                    {% else %}
                        <time datetime="1401-12-2">{{ article.jalali }}</time>
                    {% endif %}

                    <span class="articles-header-category">
                        {% for category in article.category.all %}
                            <a href="{% url 'index:article_list' category.id %}" class="blue" title="">
                            {{ category.title }}
                            </a>
                            {% if not forloop.last %},
                            {% endif %}
                        {% endfor %}
                    </span>
                </div>
                <div class="articles-content">
                    <h1><a href="{{ article.get_absolute_url }}" title="{{ article.title }}">{{ article.title }}</a>
                    </h1>
                    <p>
                        {{ article.body|slice:250|safe }}
                    </p>
                </div>
                <div class="articles-footer">
                    <ul class="articles-footer-info">

                        <li><a href="{% url 'index:like' article.slug article.id %}" class="light-link  pl-2"
                               title="">
                            <i class="pe-7s-like"></i>{{ article.likes.count }}</a>
                        </li>
                        <li><a href="#" class="light-link" title=""><i
                                class="pe-7s-comment"></i> {{ article.c }}</a>
                        </li>
                    </ul>
                    <a title="" class="btn" href="{{ article.get_absolute_url }}">ادامه مطلب</a>

                </div>
            </article>
        {% endfor %}
        <!-- PAGINATION -->
        {% include 'includes/pagination.html' %}

    </section>
</div>

templates/includes/footer.html
{% load static %}

<footer style="padding-top: 5px">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-12">
                <div class="pt-4">
                    <div class="">
                        <img src="{% static 'img/logo-grey.png' %}" alt="لوگو" class="footer-section-title-img pb-3" data-rjs="2">
                        <div class="">
                            <p class="font-primary footer-section-content-about">
                                {% for text in footer_description %}
                                    {{ text|safe }}
                                {% endfor %}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        <div class="footer-section pr-3">
                    <h3 class="footer-section-newsletter bg-light rounded">خبرنامه الکترونیکی</h3>
                    <div class="footer-section-content">
                       <p class="font-primary ">اگه میخوای از مطالب جدید اینجا مطلع بشی ایمیلتو وارد کن:</p>
                       <form class="d-flex" action="" method="post">
                          <input type="text" class="form-control w-75" placeholder="ایمیل خود را تایپ کنید">
                          <a href="#" title="Watch it" class="btn btn-small mr-5">ارسال</a>
                       </form>
                    </div>
                 </div>
        </div>
    </div>
    <!-- COPYRIGHT -->
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="copyright">
                    <ul>
                        <li><a href="{{ user.instagram }}" target="_blank" title="Instagram"><i class="icon-social_instagram_circle"></i></a></li>
                        <li><a href="{{ user.github }}" target="_blank" title="Github"><i class="icon-social_github_circle"></i></a></li>
                        <li><a href="{{ user.linkedin }}" target="_blank" title="LinkedIn"><i class="icon-social_linkedin_circle"></i></a></li>
                    </ul>
                    <p class="font-primary">&copy; برنامه نویسی شده توسط <a
                            href="{% url "index:about_me" %}" title="" class="black"
                            style="font-family: 'Microsoft Sans Serif', Tahoma, Arial, Verdana, Sans-Serif">
                        M9rsad
                    </a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- end COPYRIHT -->
</footer>

templates/includes/head_refrences.html
{% load static %}
<head>
    <!-- GENERAL -->
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ByteBlog</title>

    <!-- MY CSS -->
    <link rel="stylesheet" href="{% static "css/base.css" %}">

    <!--FONT AWESOME -->
    <script src="https://kit.fontawesome.com/3b74fce8b8.js" crossorigin="anonymous"></script>

    <!-- FAVICON -->
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "img/favicon.png" %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static "img/favicon.png" %}">
    <link rel="icon" type="image/png" href="{% static "img/favicon.png" %}" sizes="196x196">
    <link rel="icon" type="image/png" href="{% static "img/favicon.png" %}" sizes="96x96">
    <link rel="icon" type="image/png" href="{% static "img/favicon.png" %}" sizes="32x32">
</head>

templates/includes/header.html
{% load static %}


<header class="navbar-fixed-top">
    <div class="container">
        <div class="row">
            <!-- HEADER TOP -->
            <div class="col-lg-12">
                <div class="header-top">
                    <div class="header-top-logo">
                        <a href="index.html" title="لوگو"><img src="{% static "img/logo.png" %}" alt="لوگو"
                                                               data-rjs="2"></a>
                    </div>
                    <div class="header-top-text">
                        <p>
                            {% for text in header_title %}
                                {{ text.title|safe }}
                            {% endfor %}
                        </p>
                    </div>
                    <nav class="header-top-nav">
                        <ul>
                            <li class="header-top-nav-search">
                                <a href="#" class="light-link" title="جستجو کردن"><i class="pe-7s-search"></i></a>
                                <form action="{% url 'index:search' %}" method="get">
                                    <input type="text" class="form-control" name="q" placeholder="جستجو کردن...">
                                    <button href="" type="submit"><i class="pe-7s-search"></i></button>
                                </form>
                            </li>
                            <li>
                                <a href="#" class="light-link" title="منو">
                                    <div id="menu-animate-icon" class="header-top-nav-menu-icon">
                                        <span></span>
                                        <span></span>
                                        <span></span>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- end HEADER TOP -->
            <!-- HEADER NAVIGATION -->
            <div class="col-lg-12">
                <nav class="header-nav">
                    <ul>
                        <li><a href="{% url 'index:index' %}" title="صفحه اصلی">صفحه اصلی</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" title="مقالات وبلاگ">مقالات وبلاگ</a>
                            <ul class="dropdown-menu">
                                {% for category in all_categories %}
                                    {% if category.published %}
                                        <li class="{{ category.color }}"><a
                                                href="{% url 'index:article_list' category.id %}"
                                                title="{{ category.title }}">
                                            {{ category.title }}</a></li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </li>
                        <li><a href="{% url 'index:about_me' %}" title="درباره من">درباره من</a></li>
                        {#                        <li><a href="#" title="پروژه های من">پروژه های من</a></li>#}
                        <li><a href="{% url 'index:contact_us' %}" title="ارتباط با من">ارتباط با من</a></li>
                        <li></li>
{#                        <a class="float-left" style="color: #ff0500; font-size: x-small">بزودی</a>#}
{#                        <li class="buyproducts-link"><a href="" title="خرید محصولات">خرید محصولات</a></li>#}


                    </ul>
                </nav>
            </div>
        </div>
        <!-- end HEADER NAVIGATION -->
    </div>
</header>
<!-- end HEADER -->

templates/includes/js-refrences.html
{% load static %}

<script type="text/javascript" src="{% static "js/jquery-1.12.0.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/tether.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/retina.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/owl.carousel.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/webfont.js" %}"></script>

<!-- MY JAVASCRIPT -->
<script type="text/javascript" src="{% static "js/scripts.js" %}"></script>

<!-- Include jQuery -->
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

templates/includes/left-navbar.html
{% load static %}

<div class="aside-blocks col-lg-4 col-12">
    <aside class="author">
        {% for user in admin_user %}
            <img src="{{ user.image.url }}" alt="" data-rjs="2">
            <h2>{{ user.f_name }}{{ user.l_name }}</h2>
            <span class="author-info">توسعه دهنده وب</span>
            <span class="author-info">دانشجوی مهندسی کامپیوتر</span>
            <div class="social">
                <a href="{{ user.instagram }}" title="Instagram" target="_blank"><i
                        class="icon-social_instagram_circle"></i></a>
                <a href="{{ user.github }}" title="Github" target="_blank"><i
                        class="icon-social_github_circle"></i></a>
                <a href="{{ user.linkedin }}" title="LinkedIn" target="_blank"><i
                        class="icon-social_linkedin_circle"></i></a>
            </div>
        {% endfor %}
        <ul class="author-nav">
            <li><a href="{% url 'index:contact_us' %}" title=""><i class="pe-7s-comment"></i> ارتباط با من</a></li>
        </ul>
    </aside>

    <aside class="categories">
        <h2 class="aside-title">دسته بندی ها</h2>
        <ul>
            {% for category in all_categories %}
                {% if category.published %}
                    <li class="{{ category.color }}"><a href="{% url 'index:article_list' category.id %}"
                                                   title="{{ category.title }}">
                        {{ category.title }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>
    </aside>

    <aside class="advertisement">
            <a href="#"><img src="{{ ad.image }}" alt="{{ ad.name }}" data-rjs="2"></a>
    </aside>
</div>

templates/includes/pagination.html
{% if articles.has_other_pages %}
    <nav aria-label="...">
        {% if articles.has_previous %}
            <a title="" href="?page={{ articles.previous_page_number }}"
               class="btn-small-white pagination-back">قبلی</a>
        {% endif %}
        <ul class="pagination">
            {% for i in articles.paginator.page_range %}
                {% if articles.number == i %}
                    <li class="page-item active">
                        <a class="page-link" href="">{{ i }}<span class="sr-only">{{ i }}</span></a>
                    </li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
{#                    <li class="page-item"><a class="page-link" href="#">3</a></li>#}
{#                    <li class="page-item page-item-more"><a class="page-link" href="#">...</a></li>#}
{#                    <li class="page-item"><a class="page-link" href="#">25</a></li>#}
                {% endif %}
            {% endfor %}
        </ul>
        {% if articles.has_next %}
            <a title="" href="?page={{ articles.next_page_number }}" class="btn-small-white pagination-next">بعدی</a>
        {% endif %}
    </nav>
{% endif %}